### ISSUE TITLE
Detailed build instructions

### ISSUE THREAD

**Issue by hitgubmitt** [basil00/WinDivertTool#1]
Hello! Thank you for providing ways to remove WinDivert from system. From my. experience, once the driver is loaded, there is no simple way to remove it.

I've checked your instructions on how to build it:

> WinDivertTool.exe depends on the WinDivert runtime. To build, unzip the WinDivert source code into the current directory then run make. Currently only Linux cross-compilation is supported.

but I was unable to do so. For starters, `make` in not a  recognized as windows internal or external command. I tried using gcc, but there were many imports missing even after adding WinDivert source code to current directory. Can you provide more detailed instructions for those used to high level languages? I am also not entirely sure what you mean by `Linux cross-compilation`. Does that mean compiling on Linux would be more fruitful?

Thank you for your answer.

**Comment by basil00** [comment]
The WinDivert driver is easy to remove provided (1) the application using it can be found, and (2) you know how to uninstall it.  Unfortunately both (1) and (2) can be confusing for a lot of users which is why `WinDivertTool` exists to automate the process.  (That and the fact that there are some scam "uninstallers" floating around that are themselves malware/scareware).

Cross-compilation means that you use Linux to build the Windows executable using a cross compiler.  There is no specific reason for this setup other than I mainly use Linux.

You might be able to compile it using MinGW on Windows, but that is not officially supported.

Also there are pre-compiled binaries here: https://github.com/basil00/WinDivertTool/releases
